config/routes.rb
Jeeter::Application.routes.draw do
  root to: 'pages', action: :front_page
  get '/front', to: 'pages', action: :front_page

  resources :blog, only: [:index, :show] do
    resources :comments, only: [:create]
  end

  namespace :blog do
    resources :users, path: 'authors', only: [:show]
    resources :categories, only: [:show]
  end

  namespace :admin do
    get '/login', to: 'sessions#index'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    get '/', to: 'dashboards#index'
    post '/comments/approve', to: 'comments#approve'

    resources :posts, except: [:show]
    resources :categories, except: [:show]
    resources :tags, except: [:show]
    resources :uploads, except: [:show], path: 'media'
    resources :comments, except: [:show, :new, :create]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  include Searchable

  belongs_to :user
  belongs_to :post
  has_ancestry orphan_strategy: :destroy

  validates_presence_of :content, :author_name, :author_email, :post_id
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminController
  def index
    @search_term = params[:search_term]
    @comments = Comment.search_by_column(@search_term, params[:page], 'content')
  end

  def approve
    redirect_to admin_comments_path and return unless request.xhr?
    @comment = Comment.find(params[:id])

    if params[:approved] == 'true' || params[:approved] == 'false'
      @comment.update_attributes(approved: params[:approved])
      render json: @comment, status: :created
    else
      render json: { url: admin_comments_path }, status: :bad_request
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:blog_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user if logged_in?

    respond_to do |format|
      if @comment.save
        format.json do
          template = render_to_string(
            partial: 'comments/comment',
            formats: [:html],
            locals: { comment: @comment })
          render json: { comment_template: template }, status: :created
        end
        format.html { redirect_to blog_path(@post), flash: { success: 'New comment created.' } }
      else
        format.json { render json: @comment.errors, status: :bad_request }
        format.html do
          @comments = @post.comments.reload
          flash.now[:danger] = 'Please fill out all required fields.'
          set_recent_posts
          set_categories
          render 'blog/show'
        end
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :author_name, :author_email, :author_url, :parent_id)
  end
end

app/views/admin/comments/index.html.haml
%h3 Comments
.panel.panel-comments
  .panel-bar.comments-bar
    = render 'shared/admin_search', objects: @comments, terms: @search_term, object_name: 'Comments', path: method(:admin_comments_path)
  .table-responsive
    %table.table
      %thead
        %tr
          %th Author
          %th Comment
          %th In Response To
          %th Delete
      %tbody
        - @comments.each do |comment|
          %tr{'class' => (comment.approved? ? '' : 'warning')}
            %td
              %p
                = comment.author_name
                %br
                = mail_to comment.author_email
            %td
              %p
                %span.gray
                  Submitted on
                  = link_to print_date(comment.created_at), blog_path(comment.post)
                %br
                = comment.content
              .content-actions
                - if comment.approved?
                  = link_to 'Unapprove', admin_comments_approve_path, data: { id: comment.id, approved: false }
                - else
                  = link_to 'Approve', admin_comments_approve_path, data: { id: comment.id, approved: true }
                | Reply | Edit | Trash
            %td
              .comment-edit-post
                = link_to comment.post.title, edit_admin_post_path(comment.post)
              .comment-icon
                %i.glyphicon.glyphicon-comment
                %span.comment-count
                  = comment.post.comments.count
              = link_to blog_path(comment.post) do
                View Post
            %td.text-center
              = link_to admin_comment_path(comment), method: :delete, confirm: 'Are you sure? Please confirm.' do
                %i.glyphicon.glyphicon-remove