config/routes.rb
Jeeter::Application.routes.draw do
  root to: 'pages', action: :front_page
  get '/front', to: 'pages', action: :front_page

  resources :blog, only: [:index, :show] do
    resources :comments, only: [:create]
  end

  namespace :blog do
    resources :users, path: 'authors', only: [:show]
    resources :categories, only: [:show]
  end

  namespace :admin do
    get '/login', to: 'sessions#index'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    get '/', to: 'dashboards#index'
    post '/comments/approve', to: 'comments#approve'

    resources :posts, except: [:show]
    resources :categories, except: [:show]
    resources :tags, except: [:show]
    resources :uploads, except: [:show], path: 'media'
    resources :comments, except: [:show, :new, :create]
  end
end

app/views/shared/_admin_footer.html.haml
.admin-footer
  Thank you for using
  %em Jeeter
  .pull-right
    Version 0.0.1

app/views/shared/_admin_header.html.haml
%nav.navbar.navbar-inverse(role="navigation")
  .container-fluid
    .navbar-header
      %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-collapse")
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        %i.glyphicon.glyphicon-home
        Jeeter
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.dropdown
          %a.dropdown-toggle(data-toggle="dropdown")
            %i.glyphicon.glyphicon-plus
            New
            %i.caret
          %ul.dropdown-menu
            %li
              = link_to 'Post', new_admin_post_path
              = link_to 'Media', new_admin_upload_path
              %a(href="#") User
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle(data-toggle="dropdown")
            %i.glyphicon.glyphicon-user
            Howdy, Admin
          %ul.dropdown-menu
            %li
              %a(href="#") Edit My Profile
              = link_to 'Log Out', admin_logout_path

app/views/shared/_admin_search.html.haml
= form_tag path.call, method: :get, class: 'pagination-form' do
  = link_to_unless objects.first_page?, '&laquo;'.html_safe, path.call(page: 1, search_term: terms) do
    = link_to '&laquo;'.html_safe, '', class: 'disabled'
  = link_to_if objects.prev_page, '&lsaquo;'.html_safe, path.call(page: objects.prev_page, search_term: terms) do
    = link_to '&lsaquo;'.html_safe, '', class: 'disabled'
  .form-group
    = text_field_tag 'page', objects.current_page, maxlength: objects.total_pages.to_s.length, class: 'form-control'
    = "of #{objects.total_pages} "
    = hidden_field_tag 'search_term', terms, id: 'search_term_hidden'
    = submit_tag 'Submit', class: 'hidden'
  = link_to_if objects.next_page, '&rsaquo;'.html_safe, path.call(page: objects.next_page, search_term: terms) do
    = link_to '&rsaquo;'.html_safe, '', class: 'disabled'
  = link_to_unless objects.last_page?, '&raquo;'.html_safe, path.call(page: objects.total_pages, search_term: terms) do
    = link_to '&raquo;'.html_safe, '', class: 'disabled'
= form_tag path.call, method: :get, class: 'bar-search' do
  = text_field_tag 'search_term', terms, class: 'form-control'
  = submit_tag "Search #{object_name}", class: 'btn btn-default'

app/views/shared/_admin_sidebar.html.haml
%ul(role="navigation")
  %li
    = link_to admin_path do
      %i.glyphicon.glyphicon-dashboard
      Dashboard
  %li
    %a.dropdown-toggle
      %i.glyphicon.glyphicon-pushpin
      Posts
    %ul.dropdown-menu
      %li
        = link_to 'All Posts', admin_posts_path
        = link_to 'Add New', new_admin_post_path
        = link_to 'Categories', admin_categories_path
        = link_to 'Tags', admin_tags_path
  %li
    %a.dropdown-toggle
      %i.glyphicon.glyphicon-picture
      Media
    %ul.dropdown-menu
      %li
        = link_to 'Library', admin_uploads_path
        = link_to 'Add New', new_admin_upload_path
  %li
    = link_to admin_comments_path do
      %i.glyphicon.glyphicon-comment
      Comments
  %li
    %a.dropdown-toggle
      %i.glyphicon.glyphicon-user
      Users
    %ul.dropdown-menu
      %li
        %a(href="#") All Users
        %a(href="#") Add New
        %a(href="#") Your Profile
  %li
    %a
      %i.glyphicon.glyphicon-cog
      Settings

app/views/shared/_errors.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/shared/_footer.html.haml
.container
  .row
    .col-sm-9
      © #{Date.today.year} Your Site
    .col-sm-3
      %p.pull-right
        Powered by
        %em Jeeter

app/views/shared/_header.html.haml
%nav.navbar.navbar-default(role="navigation")
  .container
    .navbar-header
      %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-collapse")
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
      = link_to 'Jeeter', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Blog', blog_index_path
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Login', admin_login_path

app/views/shared/_sidebar.html.haml
.row
  .col-sm-12
    %form.form-inline.search-bar
      %input.btn.btn-default(type="submit" value="Search")
      .form-group
        %input.form-control(type="text")
  .col-sm-12
    %h4 Recent Posts
    %ul
      - @recent_posts.each do |post|
        %li
          = link_to post.title, blog_path(post)
  .col-sm-12
    %h4 Categories
    %ul
      - if @categories.empty?
        %li No Categories
      - else
        - @categories.each do |category|
          %li
            = link_to category.name, blog_category_path(category)