config/routes.rb
Jeeter::Application.routes.draw do
  root to: 'pages', action: :front_page
  get '/front', to: 'pages', action: :front_page

  resources :blog, only: [:index, :show] do
    resources :comments, only: [:create]
  end

  namespace :blog do
    resources :users, path: 'authors', only: [:show]
    resources :categories, only: [:show]
  end

  namespace :admin do
    get '/login', to: 'sessions#index'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    get '/', to: 'dashboards#index'
    post '/comments/approve', to: 'comments#approve'

    resources :posts, except: [:show]
    resources :categories, except: [:show]
    resources :tags, except: [:show]
    resources :uploads, except: [:show], path: 'media'
    resources :comments, except: [:show, :new, :create]
  end
end

app/controllers/blog/categories_controller.rb
class Blog::CategoriesController < ApplicationController
  before_action :set_recent_posts, :set_categories

  def show
    category = Category.find(params[:id])
    @posts = category.posts.blog_posts_only.page(params[:page]).per(10)
  end
end

app/controllers/blog/users_controller.rb
class Blog::UsersController < ApplicationController
  before_action :set_recent_posts, :set_categories

  def show
    user = User.find(params[:id])
    @posts = user.posts.blog_posts_only.page(params[:page]).per(10)
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :set_recent_posts, :set_categories

  def index
    @posts = Post.blog_posts_only.page(params[:page]).per(10)
  end

  def show
    @post = Post.blog_posts_only.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end
end

app/views/blog/_post.html.haml
%h3
  = link_to post.title, blog_path(post)
%p
  = is_preview ? truncate_html(post.content) : post.content.html_safe
.post-categories
  - post.categories.each do |category|
    = link_to category.name, blog_category_path(category), class: 'label label-primary'
%p.small
  Posted on
  = print_date(post.created_at)
  by
  = link_to post.user.full_name, blog_user_path(post.user)
  = "| #{post.comments.any? ? post.comments.size.to_s + ' Comments' : 'No Comments'}" if is_preview
%hr
- unless is_preview
  = render 'comments/form'
  - if @comments.any?
    .post-comments
      %h4 Comments
      = nested_comments @comments.arrange(order: :created_at)

app/views/blog/index.html.haml
.main-col.col-sm-8.col-lg-9
  %h1 Blog
  = render partial: 'post', collection: @posts, locals: { is_preview: true }
  .text-center
    = paginate @posts
.sidebar-col.col-sm-4.col-lg-3
  = render 'shared/sidebar'

app/views/blog/show.html.haml
.main-col.col-sm-8.col-lg-9
  = render 'shared/errors'
  %h1 Blog
  = render partial: 'blog/post', object: @post, locals: { is_preview: false }
.sidebar-col.col-sm-4.col-lg-3
  = render 'shared/sidebar'