config/routes.rb
Jeeter::Application.routes.draw do
  root to: 'pages', action: :front_page
  get '/front', to: 'pages', action: :front_page

  resources :blog, only: [:index, :show] do
    resources :comments, only: [:create]
  end

  namespace :blog do
    resources :users, path: 'authors', only: [:show]
    resources :categories, only: [:show]
  end

  namespace :admin do
    get '/login', to: 'sessions#index'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    get '/', to: 'dashboards#index'
    post '/comments/approve', to: 'comments#approve'

    resources :posts, except: [:show]
    resources :categories, except: [:show]
    resources :tags, except: [:show]
    resources :uploads, except: [:show], path: 'media'
    resources :comments, except: [:show, :new, :create]
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < AdminController
  before_action :set_recent_posts, :set_recent_comments

  def index; end
end

app/views/admin/dashboards/index.html.haml
%h3 Dashboard
.panel.panel-welcome
  %h4
    Welcome to the Jeeter Dashboard!
  %h4
    %span.small Here are some helpful links to edit your site:
  .row
    .col-sm-4
      %ul
        %li
          = link_to 'View your site', root_path
        %li
          = link_to 'Write a blog post', new_admin_post_path
        %li
          %a Create another post type
    .col-sm-4
      %ul
        %li
          = link_to 'Upload a file', new_admin_upload_path
        %li
          = link_to 'Create a category', admin_categories_path
        %li
          %a Review your comments
    .col-sm-4
      %ul
        %li
          %a Manage your profile
        %li
          %a Update site settings
.panel.panel-activity
  %h4
    Activity
  .row
    .col-sm-6
      %h4
        %span.small Recent Posts
      - @recent_posts.each do |post|
        %ul.list-unstyled
          %li
            %p
              = print_date(post.published_at)
              = link_to post.title, edit_admin_post_path(post)
    .col-sm-6
      %h4
        %span.small Comments
      - @recent_comments.each do |comment|
        %ul.list-unstyled
          %li
            = print_date(comment.created_at)
            %span
              = comment.author_name
              says:
            %p.gray
              = truncate(comment.content, length: 50)